---
title: "Untitled"
output: html_document
date: "2023-03-04"
---
```{r}
#put your working directory (where the code and outputs [graphs] will be stored on your computer) inside the below parenthesis
#setwd()
library(tidyverse)

#Creating dataset to match that of the client using the information from the cross-tabs breakdown of variables

region <- c(rep("NE",4576),rep("NW",14187),rep("Y&H",10864),rep("EM",11153),rep("WM",12325),rep("EE",17573),rep("L",27574),rep("SE",26831),rep("SW",18412),rep("W",7138),rep("S",303),rep("U",2009))
#For size 1=0-10k, 2 10-100k, 3 100k-1m, 4 1m-10m, 5 10m+
size <- c(rep(1,1759),rep(2,1718),rep(3,898),rep(4,179),rep(5,22),
          rep(1,5471),rep(2,5437),rep(3,2662),rep(4,521),rep(5,96),
          rep(1,4324),rep(2,4190),rep(3,1941),rep(4,356),rep(5,53),
          rep(1,5079),rep(2,4048),rep(3,1682),rep(4,283),rep(5,61),
          rep(1,5080),rep(2,4664),rep(3,2079),rep(4,418),rep(5,84),
          rep(1,7601),rep(2,6635),rep(3,2745),rep(4,463),rep(5,129),
          rep(1,8462),rep(2,9408),rep(3,7065),rep(4,2164),rep(5,475),
          rep(1,9822),rep(2,11111),rep(3,4709),rep(4,955),rep(5,234),
          rep(1,7792),rep(2,7173),rep(3,2833),rep(4,511),rep(5,103),
          rep(1,3164),rep(2,2702),rep(3,1037),rep(4,201),rep(5,34),
          rep(1,119),rep(2,117),rep(3,51),rep(4,15),rep(5,1),
          rep(1,614),rep(2,763),rep(3,473),rep(4,128),rep(5,31))

#Putting information into a dataset and setting variables to be factors
charity.data <- data.frame("id"=sample(1:152945, 152945,replace=F),
                           "region"=region,
                           "size"=size)%>%
  filter(region != "Scotland")%>% #Removing charities based in scotland from the dataset as we are not interested in looking at charities based in Scotland
  mutate(region=factor(region,levels=c("NE","NW","Y&H","EM","WM","EE","L","SE","SW","W","U"),
                       labels=c("North East","North West","Yorkshire & the Hum","East Midlands","West Midlands","East of England","London","South East","South West","Wales","Unkown")),
         size=factor(size,levels = c(1:5),labels = c("0-10k","10k-100k","100k-1m","1m-10m","10m+")))

#Adding in Nialls fake income data code that assumes charity income is uniformly distributed within the size band
# Fake income data

# Dictionary
LRangeVals <- c('0-10k'=0, '10-100k'=10, '100k-1m'=100, 
               '1m-10m'=1000, '10m+'=10000)
URangeVals <- c('0-10k'=10, '10-100k'=100, '100k-1m'=1000, 
                '1m-10m'=10000, '10m+'=500000)

# Adding values to dataframe
for (i in 1:nrow(charity.data)) {
  
  charity.data$Income[i] <- runif(1, 
                             min = LRangeVals[charity.data[i, 'size']],
                             max = URangeVals[charity.data[i, 'size']])
}


#looking at frequencies and proportions in total population of charities
table(charity.data$size)
table(charity.data$region)

prop.table(table(charity.data$size))
prop.table(table(charity.data$region))

table(charity.data$region,charity.data$size)
prop.table(table(charity.data$region,charity.data$size),margin=1) #proportions by row
prop.table(table(charity.data$region,charity.data$size),margin=2) #proportions by column
```


```{r}
#Making sampling into function so client can use much easier

## Inputs:
# charity.data: data frame that contains the id, region and size variables of all charities in the population 

# prop.lt.100: proportion of charities from each unique size region charity group with less than 100 charities that will be included in sample (number sampled from each size region group meeting this criteria is ceiling(proportion*number in group))

# prop.lt.250: proportion of charities from each unique size region charity group with between 100-249 charities that will be included in sample

# prop.lt.500: proportion of charities from each unique size region charity group with between 250-499 charities that will be included in sample

# prop.lt.1000: proportion of charities from each unique size region charity group with between 500-999 charities that will be included in sample 

# num.gt.1000: number of charities from each unique size region charity group with 1000 or more charities in them that will be included in sample (number sampled from each size region group meeting this criteria is the number chosen for this input)

# Function creates a dataset for each size region group and then randomly samples id's from each of these datasets without replacement with the number sampled depending on the number of charities within the dataset and the sampling proportions chosen. Then returns a dataset of all the charities chosen to be in the sample. 

Stratified.sample.func <- function(charity.data,prop.lt.100,prop.lt.250,prop.lt.500,prop.lt.1000,num.gt.1000){
  
    Sample.vectors <- list() # list to store sampled charities in 
  
    for (i in c("0-10k","10k-100k","100k-1m","1m-10m","10m+")){
      assign(paste0("charity.size.",i),filter(charity.data,size==i)) #creating a separate data set for each size category
      
      for (j in c("North East","North West","Yorkshire & the Hum","East Midlands","West Midlands","East of England","London","South East","South West","Wales","Unkown")){
        assign(paste0("charity.",i,".",j),filter(get(paste0("charity.size.",i)),region==j)) #creating a separate datas et for each region within each size category data set
        
        #Now sampling from within each size region data set - with the proportion sampled depending on the number of charities of the size region dataset
        if(dim(get(paste0("charity.",i,".",j)))[1]==1){
          assign(paste0("sample.charity.",i,".",j),select(get(paste0("charity.",i,".",j)),id)[[1]]) #If only 1 charity in dataset need to select that value as sample function behaves differently with only 1 input
        }
        else if(dim(get(paste0("charity.",i,".",j)))[1]<100){
          assign(paste0("sample.charity.",i,".",j),sample(select(get(paste0("charity.",i,".",j)),id)[[1]],size=ceiling(dim(get(paste0("charity.",i,".",j)))[1]*prop.lt.100))) #sampling for datasets containing less than 100 charities
        }
        else if(dim(get(paste0("charity.",i,".",j)))[1]<250){
          assign(paste0("sample.charity.",i,".",j),sample(select(get(paste0("charity.",i,".",j)),id)[[1]],size=ceiling(dim(get(paste0("charity.",i,".",j)))[1]*prop.lt.250))) #sampling for datasets containing 100-249 charities
        }
        else if(dim(get(paste0("charity.",i,".",j)))[1]<500){
          assign(paste0("sample.charity.",i,".",j),sample(select(get(paste0("charity.",i,".",j)),id)[[1]],size=ceiling(dim(get(paste0("charity.",i,".",j)))[1]*prop.lt.500))) #sampling for datasets containing 250-499 charities
        }
        else if(dim(get(paste0("charity.",i,".",j)))[1]<1000){
          assign(paste0("sample.charity.",i,".",j),sample(select(get(paste0("charity.",i,".",j)),id)[[1]],size=ceiling(dim(get(paste0("charity.",i,".",j)))[1]*prop.lt.1000)))  #sampling for datasets containing 500-999 charities
        }
        else{
          assign(paste0("sample.charity.",i,".",j),sample(select(get(paste0("charity.",i,".",j)),id)[[1]],size=num.gt.1000)) #sampling for datasets containing 1000 or more charities
        }
        Sample.vectors <- append(Sample.vectors,get(paste0("sample.charity.",i,".",j)),after=length(Sample.vectors)) #putting sampled charities into 1 list
      }
    }
    Sample.vectors<-unlist(Sample.vectors) 
    
    #Matching sampled charities with original data
    sampled.charities.df <- merge(data.frame("id"=Sample.vectors),charity.data,by="id")
    
    return(sampled.charities.df)
}
#sampling using stratifying function and chosen proportions to allow 'good' (representative) sized sample from each strata within the 7000 sample size limit
sample.dataset<-Stratified.sample.func(charity.data,1,0.8,0.45,0.15,120)
```

```{r}
#Using sample to estimate the total income

# Summary stats of actual frequencies of each strata
table_actual_freq <- table(charity.data$region,charity.data$size)
#investigating sampled dataset frequencies 
table_sample_freq<- table(sample.dataset$region,sample.dataset$size)

#propotion of each strata included in the sample
proportion_of_strata_sampled <- round(table_sample_freq/table_actual_freq,3)
#weights are inverse of the proportion of strata population sampled (e.g. the weight of a strata with 50% of population in the sample has a weight of 2)
weighting<-table_actual_freq/table_sample_freq

#Performing calculations 
#Creating dataset which calculates the total income of each strata in the sample(sums up the income of charities in the same strata) and the number of charities in each strata in the sample
sample.strata.income <- sample.dataset%>%
  group_by(size,region)%>%
  summarise(sample.income=sum(Income),sample.n=n())

#Creating dataset which calculates the total income of each strata in the population (sums up the income of charities in the same strata) and the number of charities in each strata in the population (where population is all charities that we want to investigate)
pop.strata.income <- charity.data%>%
  group_by(size,region)%>%
  summarise(pop.income=sum(Income),pop.n=n())

#Estimating the total income of each strata by multiplying the sample income by the weights of each sample
est.strata.income <- merge(sample.strata.income,pop.strata.income,by=c("size","region"))%>%
  mutate(est.income = pop.n/sample.n*sample.income,
         perc.difference = abs(1-(est.income/pop.income))*100)%>%
  mutate(perc.sample=sample.n/pop.n*100)

#reporting estimates and absolute percent differences for each strata
est.strata.income%>%
  mutate(prop.sample = sample.n/pop.n)%>%
  select(size,region,sample.n,pop.n,sample.income,prop.sample,pop.income,est.income,perc.difference)%>%
  kableExtra::kable(digits=3)%>%
  kableExtra::kable_classic()

#repeating but grouping by region (strata is only region)
est.region.income <- est.strata.income%>%
  group_by(region)%>%
  summarise(sample.region.n=sum(sample.n),
            pop.region.n=sum(pop.n),
            sample.region.income=sum(sample.income),
            est.region.income=sum(est.income),
            actual.region.income=sum(pop.income),
            perc.difference = abs(1-(est.region.income/actual.region.income))*100)%>%
  mutate(perc.sample=sample.region.n/pop.region.n*100)

#nice table output
est.region.income %>%
  kableExtra::kable(digits=3)%>%
  kableExtra::kable_classic()

#repeating but grouping by size (strata is only size)
est.size.income <- est.strata.income%>%
  group_by(size)%>%
  summarise(sample.size.n=sum(sample.n),
            pop.size.n=sum(pop.n),
            sample.size.income=sum(sample.income),
            est.size.income=sum(est.income),
            actual.size.income=sum(pop.income),
            perc.difference = abs(1-(est.size.income/actual.size.income))*100)%>%
  mutate(perc.sample=sample.size.n/pop.size.n*100)

#nice table output
est.size.income %>%
  kableExtra::kable(digits=3)%>%
  kableExtra::kable_classic()
```

```{r}
# Creating sample diagnostic function to find average absolute percent difference in income between estimated income using the sample and the true income when performing sampling method n times

#Inputs:
#loop.n number of times to perform sampling method
#Other inputs are identical to those of same name in stratified sampling function

sample_diagnostic_func<-function(loop.n,charity.data,prop.lt.100,prop.lt.250,prop.lt.500,prop.lt.1000,num.gt.1000){

#setting up vectors to store percent differences when stratified by either region or size
perc.diff.region <- rep(0,11)
perc.diff.size <- rep(0,5)

for (i in 1:loop.n){
  sample.data <- Stratified.sample.func(charity.data,prop.lt.100,prop.lt.250,prop.lt.500,prop.lt.1000,num.gt.1000)
  
 #Creating dataset which calculates the total income of each strata (sums up the income of charities in the same strata) in the sample and the number of charities in each strata in the sample
sample.strata.income <- sample.data%>%
  group_by(size,region)%>%
  summarise(sample.income=sum(Income),sample.n=n(), .groups = 'drop')

#Creating dataset which calculates the total income of each strata (sums up the income of charities in the same strata) in the population and the number of charities in each strata in the population (where population is all charities that we want to investigate)
pop.strata.income <- charity.data%>%
  group_by(size,region)%>%
  summarise(pop.income=sum(Income),pop.n=n(), .groups = 'drop')

#Estimating the total income of each strata by multiplying the sample income by the weights of each sample
est.strata.income <- merge(sample.strata.income,pop.strata.income,by=c("size","region"))%>%
  mutate(est.income = pop.n/sample.n*sample.income,
         perc.difference = abs(1-(est.income/pop.income))*100)


#repeating but grouping by region (strata is only region)
est.region <- est.strata.income%>%
  group_by(region)%>%
  summarise(est.region.income=sum(est.income),
            actual.region.income=sum(pop.income),
            perc.difference = abs(1-(est.region.income/actual.region.income))*100, .groups = 'drop')

#repeating but grouping by size (strata is only size)
est.size <- est.strata.income%>%
  group_by(size)%>%
  summarise(est.size.income=sum(est.income),
            actual.size.income=sum(pop.income),
            perc.difference = abs(1-(est.size.income/actual.size.income))*100, .groups = 'drop')
  
#adding absolute percent differences to those in previous loops  
perc.diff.region <- perc.diff.region+est.region$perc.difference
perc.diff.size <- perc.diff.size+est.size$perc.difference
}
#putting inot dataframes and calulating average abs percent difference by dividing my number of loops
region.diag<-data.frame("region"= c("North East","North West","Yorkshire & the Hum","East Midlands","West Midlands","East of England","London","South East","South West","Wales","Unkown"),
                        "perc average abs error"=perc.diff.region/loop.n)
size.diag<-data.frame("size"= c("0-10k","10k-100k","100k-1m","1m-10m","10m+"),"perc average abs error"=perc.diff.size/loop.n)

return(list(region.diag,size.diag))
}

#running function (note doing 1000 iterations takes a long time thus saved result in excel spreadsheet that can be accessed from github)
sample.diagnostics <- sample_diagnostic_func(1000,charity.data,1,0.8,0.45,0.15,120)
```

```{r}
#extracting region and size diagnostics from the function output
sample.diag.region<-sample.diagnostics[[1]]%>%
  mutate(perc.average.abs.error=round(perc.average.abs.error,3))

sample.diag.size<-sample.diagnostics[[2]]%>%
  mutate(perc.average.abs.error=round(perc.average.abs.error,3))


#saving diagnostics to spreadsheet
writexl::write_xlsx(sample.diag.region,"Sample region strata diagnostics.xlsx")
writexl::write_xlsx(sample.diag.size,"Sample size strata diagnostics.xlsx")
```


```{r}
#Creating simple graphs to display percent of strata sampled by region, income band and both income band and region

region.plot <- ggplot(data=est.region.income,aes(x=region,y=perc.sample,fill=region))+
  geom_bar(stat = "identity")+
  geom_text(aes(label = paste0(round(perc.sample,2),"%")), vjust = -2, colour = "black")+
  geom_text(aes(label = paste0("(N=",sample.region.n,")")), vjust = -.5, colour = "black")+
  labs(title = "Percent of each region sampled",x="Region", y="Percent of each region included in the sample",
       caption="The proportion/number of charities chosen to be included in the sample from each strata was decided by values the consultants selected (values mentioned earlier in presentation), \n selecting different values would yield different resulting percentages sampled")+
  ylim(0,100)+
  theme_bw()+
  theme(axis.title.x = element_text(vjust = 0, size = 20),
        axis.title.y = element_text(vjust = 2, size = 20),
        plot.title = element_text(face = "bold",
                                  margin = margin(10, 0, 10, 0),
                                  size = 32,
                                  hjust=0.5), 
        legend.position = "none",
        axis.text.y = element_text(size = 16),
        axis.text.x = element_text(angle = 50, vjust = 1, hjust = 1,size=12),
        plot.caption = element_text(hjust = 0.5))


size.plot <- ggplot(data=est.size.income,aes(x=size,y=perc.sample,fill=size))+
  geom_bar(stat = "identity")+
  geom_text(aes(label = paste0(round(perc.sample,2),"%")), vjust = -2, colour = "black",size=8)+
  geom_text(aes(label = paste0("(N=",sample.size.n,")")), vjust = -.5, colour = "black",size=8)+
  labs(title = "Percent of each income band sampled",x="Income band (£)", y="Percent of each income band included in the sample",
       caption="The proportion/number of charities chosen to be included in the sample from each strata was decided by values the consultants selected (values mentioned earlier in presentation), \n selecting different values would yield different resulting percentages sampled")+
  ylim(0,100)+
  theme_bw()+
  theme(axis.title.x = element_text(vjust = 0, size = 20),
        axis.title.y = element_text(vjust = 1, size = 20),
        plot.title = element_text(face = "bold",
                                  margin = margin(10, 0, 10, 0),
                                  size = 32,
                                  hjust=0.5), 
        legend.position = "none",
        axis.text.y = element_text(size = 16),
        axis.text.x = element_text(size=12),
        plot.caption = element_text(hjust = 0.5))

strata.plot <- ggplot(data=est.strata.income,aes(x=region,y=perc.sample,fill=region))+
  geom_text(aes(label = paste0(round(perc.sample,2),"%")), vjust = -1.75, colour = "black",size=2)+
  geom_text(aes(label = paste0("(N=",sample.n,")")), vjust = -0.25, colour = "black",size=2)+
  geom_bar(stat = "identity",position="dodge")+
  theme_bw()+
  theme(axis.title.x = element_text(vjust = 0, size = 20),
        axis.title.y = element_text(vjust = 2, size = 20),
        plot.title = element_text(face = "bold",
                                  margin = margin(10, 0, 10, 0),
                                  size = 32), 
        legend.position = "none",
        axis.text.y = element_text(size = 16),
        axis.text.x = element_text(angle = 90, vjust = 1, hjust = 1),
        plot.caption = element_text(hjust = 0.5))+
  labs(x="Region of charity",y="Percent of charities for each region within each \n income band included in the sample",
       caption="The proportion/number of charities chosen to be included in the sample from each strata was decided by values the consultants selected (values mentioned earlier in presentation), \n selecting different values would yield different resulting percentages sampled")+
  facet_wrap(vars(size))
```


```{r}
#Saving plots to pdf

pdf("size band sample plot.pdf",
    width=14,
    height=10)
size.plot
dev.off()

pdf("region sample plot.pdf",
    width=14,
    height=10)
region.plot
dev.off()

pdf("strata sample plot.pdf",
    width=14,
    height=10)
strata.plot
dev.off()
```